# Generated by Django 4.1.6 on 2023-10-24 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("x", models.FloatField(default=0.0)),
                ("y", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="location",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Ustad",
            fields=[
                ("online", models.BooleanField(default=False)),
                (
                    "visibility_radius",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "jop_type",
                    models.CharField(
                        choices=[
                            ("F", "Fix Rate"),
                            ("H", "Hourly"),
                            ("D", "Daily"),
                            ("M", "Monthly"),
                        ],
                        default="H",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ustad",
                        to="services.profession",
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("end", models.DateTimeField(auto_now=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "jop_type",
                    models.CharField(
                        choices=[
                            ("F", "Fix Rate"),
                            ("H", "Hourly"),
                            ("D", "Daily"),
                            ("M", "Monthly"),
                        ],
                        default="H",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Rejected"),
                            ("A", "Accepted"),
                            ("S", "Start"),
                            ("C", "Complete"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ustad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request",
                        to="services.ustad",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "rate",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="order_review",
                        serialize=False,
                        to="services.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
