# Generated by Django 4.1.6 on 2024-01-12 12:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('visibility_radius', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jop_type', models.CharField(choices=[('F', 'Fix Rate'), ('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly')], default='F', max_length=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('jop_type', models.CharField(choices=[('F', 'Fix Rate'), ('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly')], default='F', max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled'), ('R', 'Rejected'), ('A', 'Accepted'), ('F', 'Finished')], default='P', max_length=1)),
                ('requirements', models.TextField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='services.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gig',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gig', to='services.profession'),
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_review', serialize=False, to='services.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
